Translatables:
  FortuneCookieTranslatable: "Glückskeks" # Fortune Cookie
  FortuneTellingTranslatable: "Weissagung" # Fortune Telling
  FortuneCookieRightClickTranslatable: "Rechts-Klick zum öffnen" # Right-click to open
  WarningNotEnoughInvSlots: "Du hast nicht genügend Platz im Inventar." # You don't have enough space in your inventory.
FortuneCookieHead:
  FortuneCookieHeadUUID: "66fafbdd-bc73-42ae-8124-73ab2fbfbf13"
  FortuneCookieHeadOwnerName: "Glückskeks" #Fortune Cookie
  FortuneCookieTextureProperties: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDgwZDBjZGY5NDgxOTY2YjM4NGMzNmIzMWE3N2RjMGViMzdhMDg5Y2I4YWM2Nzk1NzkyMWFjNjkyNjU1ODY5In19fQ=="
FortuneTellingsList: # Add List of Fortune Tellings here !
  - "This is a fortune telling."
  - "Banana"
  - "Strawberry"
# - more stuff here
# -
# -